apiVersion: v2
name: manufacturing-datacenter-install
description: Helm chart to deploy software infrastructure services on the Datacenter
type: application
version: 0.0.1
appVersion: "1.0.0"
dependencies:
  - name: influxdb2
    version: 2.1.0
    condition: influxdb2.enabled
    tags:
      - influxdb2
