
---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: keystore-secret-bootstrap
type: Opaque

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bootstrap
spec:
  commonName: plant-manager-service.manufacturing-dev.qiot-project.io
  dnsNames:
  - plant-manager-service.manufacturing-dev.qiot-project.io
  issuerRef:
    name: vault-issuer-vault
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: keystore-secret-bootstrap
  secretName: bootstrap-certificate
